import type { AppProps } from "next/app"
import Head from 'next/head'
import router from 'next/router'
import { JSX } from 'react'
import ym, { YMInitializer } from 'react-yandex-metrika'
import "../styles/globals.css"

router.events.on('routeChangeComplete', (url: string) => {
  if (typeof window !== 'undefined') {
    ym('hit', url);
  }
})

export default function App({ Component, pageProps, router }: AppProps): JSX.Element {
  return <>
      <Head>
        <title>My top наш лучший топ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://mc.yandex.ru" />
        <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
        <meta property='og:locale' content="ru_RU" />
      </Head>
      <YMInitializer 
        accounts={[]}
        options={{ webvisor: true, defer: true }}
        version='2'
      />
     <Component {...pageProps} />
  </>
}